Tack för att du bidrar till vårt lokaliserade innehåll! 
Alla bidrag till vårt innehåll måste följa de här riktlinjerna:
1. [Microsoft Language Style Guide](https://www.microsoft.com/Language/StyleGuides) som beskriver hur texten ska se ut vid översättning från engelska till ett annat språk.
2. [Microsoft Language Portal](https://www.Microsoft.com/Language) tillhandahåller teknikrelaterade **termer** på engelska med motsvarande översättning, som ska användas i alla Microsoft-produkter.
När du går med i vår ständigt växande lokaliseringscommunity kan du läsa mer om lokaliseringsprogrammet och om andra sätt som du kan bidra till programmet genom att gå till [Community Localization Wiki](https://github.com/Microsoft/Localization/wiki). PR-godkännandeprocessen finns även på den här sidan, tillsammans med några tips för <PR-hantering>.
Fortsätt att bidra och nå högre nivåer på vår [Contributors’ Leaderboard](https://microsoftl10n.GitHub.IO/) när du får poäng för dina <lokaliserings>bidrag!

Microsoft Developer Relationship International Group
